# Generated by Django 4.1.7 on 2023-03-31 23:02

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_category_gallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=gallery.models.get_image_path),
        ),
    ]
